### ISSUE TITLE
Can't understand how to use DFormat (Ubuntu 15.04)

### ISSUE THREAD

**Issue by drug007** [dmi7ry/dfmt-sublime#1]
I installed DFormat, but nothing happened/is happening. I tried `Ctrl-Alt-F` but no result. What should I do to get the result?

**Comment by dmi7ry** [comment]
What is your OS?

**Comment by dmi7ry** [comment]
Do you have `DLang` in the Sublime main menu?
![dformat_sublime](https://cloud.githubusercontent.com/assets/1731751/23494806/8a10ffcc-ff47-11e6-9755-2d5cd4db2d79.png)

I checked on Linux Mint + ST2 and I have `DLang / Dformat` option.

Also you can define a hotkey for it. Open `Preferences / Key Bindings - User` and add line like [here](https://github.com/dmi7ry/dfmt-sublime/blob/master/Default%20%28Windows%29.sublime-keymap)

**Comment by drug007** [comment]
Yes, I have this menu item and now I understand how to use the plug-in. It would be nice to mention it in the readme. Thanks!

P.S. the default hotkey `Ctrl-Alt-f` doesn't work
